# Generated by Django 5.2 on 2025-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("street_address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=10)),
                ("telephone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_survey", models.DateField()),
                ("liked_most", models.CharField(max_length=500)),
                ("source_of_interest", models.CharField(max_length=100)),
                ("likelihood", models.CharField(max_length=50)),
                ("comments", models.TextField(blank=True)),
            ],
        ),
    ]
