# Generated by Django 5.2 on 2025-04-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsurvey",
            name="liked_most",
            field=models.JSONField(default=list),
        ),
    ]
