# Generated by Django 5.2 on 2025-04-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_alter_studentsurvey_liked_most"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsurvey",
            name="liked_most",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
